### ISSUE TITLE
Option for XP Per Character

### ISSUE THREAD

**Issue by colgraff** [manuelVo/foundryvtt-award-xp#16]
In the Pathfinder 2e system you generally hand out XP evenly for all characters and encounters are made with that number in mind. When XP is handed out you give each character the value of the encounter instead of giving out a lump amount to be split between all.

It would be good to have an option to specify that the XP amount is per character, for example:

The encounter is a moderate one for the players so they get 80 XP each. The GM has to calculate 80 x 4 = 320, then put 320 in the XP field, the module splits that 4 ways so 80 XP each. 

If there was an option that specified the XP was on a per character basis you could just enter 80 and 80 XP would get handed to each character.

**Comment by jhubsharp** [comment]
I tested this on my end by adding a setting to allow the GM to decide if XP should be split or not (defaulted to false for PF2 and true for the other systems). Then I just check that setting to see if XP should be divided or not. Works like a charm on my local Foundry, though I did not test the default logic on other systems and I did not add non-English translations. 

@manuelVo happy to push up a branch if you want to pull it in.

**Comment by manuelVo** [comment]
@jhubsharp sure, feel free to create a pr

**Comment by jhubsharp** [comment]
Looks like I can't push a branch, unless you want in develop?

**Comment by manuelVo** [comment]
Github will prevent you from pushing to this repository in general (since it's mine). The process for contributing changes is usually as follows:

- Fork the repository into your own profile (this can be done via the fork button on the top right of the github interface)
- Set your fork as the origin of your local clone
- Push your changes to some branch in your forked repository
- Create a PR for the branch you've pushed (it's pretty simple to do. Github will recognize the newly pushed branch and suggest to do so)
- Then I can review the changes and pull them into this repository

**Comment by jhubsharp** [comment]
It's up for you to take a look at.
